// <auto-generated />
using System;
using core3._1_mvc_monolith.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace core3._1_mvc_monolith.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20190805192600_AddShoppingCartItem")]
    partial class AddShoppingCartItem
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0-preview6.19304.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("core3._1_mvc_monolith.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName");

                    b.Property<string>("Description");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Spicy Pizzas"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Meat Pizzas"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Vegetarian Pizzas"
                        });
                });

            modelBuilder.Entity("core3._1_mvc_monolith.Models.Pizza", b =>
                {
                    b.Property<int>("PizzaId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AllergyInformation");

                    b.Property<int>("CategoryId");

                    b.Property<string>("ImageThumbnailPath");

                    b.Property<string>("ImagePath");

                    b.Property<bool>("InStock");

                    b.Property<bool>("IsPizzaOfTheWeek");

                    b.Property<string>("LongDescription");

                    b.Property<string>("Name");

                    b.Property<decimal>("Price");

                    b.Property<string>("ShortDescription");

                    b.HasKey("PizzaId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Pizzas");

                    b.HasData(
                        new
                        {
                            PizzaId = 1,
                            AllergyInformation = "",
                            CategoryId = 1,
                            ImagePath = "~/Images/pizzas/cheese-pizza.png",
                            ImageThumbnailPath = "~/Images/thumbnails/cheese-small.png",
                            InStock = true,
                            IsPizzaOfTheWeek = true,
                            LongDescription = "In a glass or plastic bowl, combine yeast, water, and sugar (the water can just be water from the tap, make sure it's below 100°F). Stir to dissolve the yeast and let the yeast bloom for 15 minutes. Stir in 1 cup flour, add salt, and then stir in another cup of flour (the remaining cup of flour will be your bench flour and added flour). Dump mixture onto kneading board and work in last cup of flour, kneading until dough is soft and elastic, but not sticky. Form dough into a ball. In another bowl, pour in the 1 tbsp olive oil and spread around. Coat ball of dough with oil and cover bowl with a damp towel and let dough rise for 40 minutes.",
                            Name = "Cheese Pizza",
                            Price = 15.50m,
                            ShortDescription = "Our famous Cheese Pizzas!"
                        },
                    new
                    {
                        PizzaId = 2,
                        AllergyInformation = "",
                        CategoryId = 1,
                        ImagePath = "~/Images/pizzas/cheese-pizza.png",
                        ImageThumbnailPath = "~/Images/thumbnails/cheese-small.png",
                        InStock = true,
                        IsPizzaOfTheWeek = false,
                        LongDescription = "In a glass or plastic bowl, combine yeast, water, and sugar (the water can just be water from the tap, make sure it's below 100°F). Stir to dissolve the yeast and let the yeast bloom for 15 minutes. Stir in 1 cup flour, add salt, and then stir in another cup of flour (the remaining cup of flour will be your bench flour and added flour). Dump mixture onto kneading board and work in last cup of flour, kneading until dough is soft and elastic, but not sticky. Form dough into a ball. In another bowl, pour in the 1 tbsp olive oil and spread around. Coat ball of dough with oil and cover bowl with a damp towel and let dough rise for 40 minutes.",
                        Name = "Cheese Pizza",
                        Price = 16.00m,
                        ShortDescription = "Our famous Cheese Pizzas!"
                    },
                      new
                      {
                          PizzaId = 3,
                          AllergyInformation = "",
                          CategoryId = 1,
                          ImagePath = "~/Images/pizzas/chicken-cheese-pizza.png",
                          ImageThumbnailPath = "~/Images/thumbnails/chicken-small.png",
                          InStock = true,
                          IsPizzaOfTheWeek = true,
                          LongDescription = "In a glass or plastic bowl, combine yeast, water, and sugar (the water can just be water from the tap, make sure it's below 100°F). Stir to dissolve the yeast and let the yeast bloom for 15 minutes. Stir in 1 cup flour, add salt, and then stir in another cup of flour (the remaining cup of flour will be your bench flour and added flour). Dump mixture onto kneading board and work in last cup of flour, kneading until dough is soft and elastic, but not sticky. Form dough into a ball. In another bowl, pour in the 1 tbsp olive oil and spread around. Coat ball of dough with oil and cover bowl with a damp towel and let dough rise for 40 minutes.",
                          Name = "Chicken Trio Pizza",
                          Price = 15.00m,
                          ShortDescription = "3 Chickens made it!"
                      },
                        new
                        {
                            PizzaId = 4,
                            AllergyInformation = "",
                            CategoryId = 1,
                            ImagePath = "~/Images/pizzas/chicken-cheese-pizza.png",
                            ImageThumbnailPath = "~/Images/thumbnails/chicken-small.png",
                            InStock = true,
                            IsPizzaOfTheWeek = false,
                            LongDescription = "In a glass or plastic bowl, combine yeast, water, and sugar (the water can just be water from the tap, make sure it's below 100°F). Stir to dissolve the yeast and let the yeast bloom for 15 minutes. Stir in 1 cup flour, add salt, and then stir in another cup of flour (the remaining cup of flour will be your bench flour and added flour). Dump mixture onto kneading board and work in last cup of flour, kneading until dough is soft and elastic, but not sticky. Form dough into a ball. In another bowl, pour in the 1 tbsp olive oil and spread around. Coat ball of dough with oil and cover bowl with a damp towel and let dough rise for 40 minutes.",
                            Name = "Chicken Trio Pizza",
                            Price = 18.95m,
                            ShortDescription = "3 Chickens made it!"
                        },
                          new
                          {
                              PizzaId = 5,
                              AllergyInformation = "",
                              CategoryId = 1,
                              ImagePath = "~/Images/pizzas/pepperoni-pizza.png",
                              ImageThumbnailPath = "~/Images/thumbnails/pepperoni-small.png",
                              InStock = true,
                              IsPizzaOfTheWeek = true,
                              LongDescription = "In a glass or plastic bowl, combine yeast, water, and sugar (the water can just be water from the tap, make sure it's below 100°F). Stir to dissolve the yeast and let the yeast bloom for 15 minutes. Stir in 1 cup flour, add salt, and then stir in another cup of flour (the remaining cup of flour will be your bench flour and added flour). Dump mixture onto kneading board and work in last cup of flour, kneading until dough is soft and elastic, but not sticky. Form dough into a ball. In another bowl, pour in the 1 tbsp olive oil and spread around. Coat ball of dough with oil and cover bowl with a damp towel and let dough rise for 40 minutes.",
                              Name = "Pepparoni Chedder Pizza",
                              Price = 17.50m,
                              ShortDescription = "Have a party with this Pizza!"
                          },
                            new
                            {
                                PizzaId = 6,
                                AllergyInformation = "",
                                CategoryId = 1,
                                ImagePath = "~/Images/pizzas/meat-pizza.png",
                                ImageThumbnailPath = "~/Images/thumbnails/meat-small.png",
                                InStock = true,
                                IsPizzaOfTheWeek = false,
                                LongDescription = "In a glass or plastic bowl, combine yeast, water, and sugar (the water can just be water from the tap, make sure it's below 100°F). Stir to dissolve the yeast and let the yeast bloom for 15 minutes. Stir in 1 cup flour, add salt, and then stir in another cup of flour (the remaining cup of flour will be your bench flour and added flour). Dump mixture onto kneading board and work in last cup of flour, kneading until dough is soft and elastic, but not sticky. Form dough into a ball. In another bowl, pour in the 1 tbsp olive oil and spread around. Coat ball of dough with oil and cover bowl with a damp towel and let dough rise for 40 minutes.",
                                Name = "Spicy Meat Pizza",
                                Price = 12.95m,
                                ShortDescription = "If you can handle spice!"
                            },
                              new
                              {
                                  PizzaId = 7,
                                  AllergyInformation = "",
                                  CategoryId = 1,
                                  ImagePath = "~/Images/pizzas/meat-pizza.png",
                                  ImageThumbnailPath = "~/Images/thumbnails/meat-small.png",
                                  InStock = true,
                                  IsPizzaOfTheWeek = true,
                                  LongDescription = "In a glass or plastic bowl, combine yeast, water, and sugar (the water can just be water from the tap, make sure it's below 100°F). Stir to dissolve the yeast and let the yeast bloom for 15 minutes. Stir in 1 cup flour, add salt, and then stir in another cup of flour (the remaining cup of flour will be your bench flour and added flour). Dump mixture onto kneading board and work in last cup of flour, kneading until dough is soft and elastic, but not sticky. Form dough into a ball. In another bowl, pour in the 1 tbsp olive oil and spread around. Coat ball of dough with oil and cover bowl with a damp towel and let dough rise for 40 minutes.",
                                  Name = "Spicy Meat Pizza",
                                  Price = 19.00m,
                                  ShortDescription = "Real Spice Real Pizza!"
                              },
                                new
                                {
                                    PizzaId = 8,
                                    AllergyInformation = "",
                                    CategoryId = 1,
                                    ImagePath = "~/Images/pizzas/veg-pizza.png",
                                    ImageThumbnailPath = "~/Images/thumbnails/veg-small.png",
                                    InStock = true,
                                    IsPizzaOfTheWeek = true,
                                    LongDescription = "In a glass or plastic bowl, combine yeast, water, and sugar (the water can just be water from the tap, make sure it's below 100°F). Stir to dissolve the yeast and let the yeast bloom for 15 minutes. Stir in 1 cup flour, add salt, and then stir in another cup of flour (the remaining cup of flour will be your bench flour and added flour). Dump mixture onto kneading board and work in last cup of flour, kneading until dough is soft and elastic, but not sticky. Form dough into a ball. In another bowl, pour in the 1 tbsp olive oil and spread around. Coat ball of dough with oil and cover bowl with a damp towel and let dough rise for 40 minutes.",
                                    Name = "Vegetarian Pizza",
                                    Price = 14.50m,
                                    ShortDescription = "We care about all!"
                                },
                        new
                        {
                            PizzaId = 9,
                            AllergyInformation = "",
                            CategoryId = 1,
                            ImagePath = "~/Images/pizzas/pepperoni-pizza.png",
                            ImageThumbnailPath = "~/Images/thumbnails/pepperoni-small.png",
                            InStock = true,
                            IsPizzaOfTheWeek = true,
                            LongDescription = "In a glass or plastic bowl, combine yeast, water, and sugar (the water can just be water from the tap, make sure it's below 100°F). Stir to dissolve the yeast and let the yeast bloom for 15 minutes. Stir in 1 cup flour, add salt, and then stir in another cup of flour (the remaining cup of flour will be your bench flour and added flour). Dump mixture onto kneading board and work in last cup of flour, kneading until dough is soft and elastic, but not sticky. Form dough into a ball. In another bowl, pour in the 1 tbsp olive oil and spread around. Coat ball of dough with oil and cover bowl with a damp towel and let dough rise for 40 minutes.",
                            Name = "Pepparoni Chedder Pizza",
                            Price = 17.50m,
                            ShortDescription = "Have a party with this Pizza!"
                        },
                        new
                        {
                            PizzaId = 10,
                            AllergyInformation = "",
                            CategoryId = 1,
                            ImagePath = "~/Images/pizzas/cheese-pizza.png",
                            ImageThumbnailPath = "~/Images/thumbnails/cheese-small.png",
                            InStock = true,
                            IsPizzaOfTheWeek = false,
                            LongDescription = "In a glass or plastic bowl, combine yeast, water, and sugar (the water can just be water from the tap, make sure it's below 100°F). Stir to dissolve the yeast and let the yeast bloom for 15 minutes. Stir in 1 cup flour, add salt, and then stir in another cup of flour (the remaining cup of flour will be your bench flour and added flour). Dump mixture onto kneading board and work in last cup of flour, kneading until dough is soft and elastic, but not sticky. Form dough into a ball. In another bowl, pour in the 1 tbsp olive oil and spread around. Coat ball of dough with oil and cover bowl with a damp towel and let dough rise for 40 minutes.",
                            Name = "Cheese Pizza",
                            Price = 16.00m,
                            ShortDescription = "Our famous Cheese Pizzas!"
                        },
                        new
                        {
                            PizzaId = 11,
                            AllergyInformation = "",
                            CategoryId = 1,
                            ImagePath = "~/Images/pizzas/chicken-cheese-pizza.png",
                            ImageThumbnailPath = "~/Images/thumbnails/chicken-small.png",
                            InStock = true,
                            IsPizzaOfTheWeek = false,
                            LongDescription = "In a glass or plastic bowl, combine yeast, water, and sugar (the water can just be water from the tap, make sure it's below 100°F). Stir to dissolve the yeast and let the yeast bloom for 15 minutes. Stir in 1 cup flour, add salt, and then stir in another cup of flour (the remaining cup of flour will be your bench flour and added flour). Dump mixture onto kneading board and work in last cup of flour, kneading until dough is soft and elastic, but not sticky. Form dough into a ball. In another bowl, pour in the 1 tbsp olive oil and spread around. Coat ball of dough with oil and cover bowl with a damp towel and let dough rise for 40 minutes.",
                            Name = "Chicken Trio Pizza",
                            Price = 18.95m,
                            ShortDescription = "3 Chickens made it!"
                        });
                });

            modelBuilder.Entity("core3._1_mvc_monolith.Models.ShoppingCartItem", b =>
                {
                    b.Property<int>("ShoppingCartItemId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount");

                    b.Property<int?>("PizzaId");

                    b.Property<string>("ShoppingCartId");

                    b.HasKey("ShoppingCartItemId");

                    b.HasIndex("PizzaId");

                    b.ToTable("ShoppingCartItems");
                });

            modelBuilder.Entity("core3._1_mvc_monolith.Models.Pizza", b =>
                {
                    b.HasOne("core3._1_mvc_monolith.Models.Category", "Category")
                        .WithMany("Pizzas")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("core3._1_mvc_monolith.Models.ShoppingCartItem", b =>
                {
                    b.HasOne("core3._1_mvc_monolith.Models.Pizza", "Pizza")
                        .WithMany()
                        .HasForeignKey("PizzaId");
                });
#pragma warning restore 612, 618
        }
    }
}
